### ISSUE TITLE
Fabric Port copy of Chipped x Create Fabric

### ISSUE THREAD

**Issue by souldbminersmwc** [BrayDog2010/Crafting-Recipes-For-Create#3]
Really? Looking through the code, it does not seem that there is much difference between CHCF and this mod. In fact, it is structured very similarly to Chipped x Create Fabric

**Comment by BrayDog2010** [comment]
No I made the fabric port

**Comment by souldbminersmwc** [comment]
Then what about the class names? They are idential to CHCF

**Comment by BrayDog2010** [comment]
That's because I used a Minecraft mod maker

**Comment by souldbminersmwc** [comment]
Still odd that the names are the same. Plus the code inside looks surprisingly similar

**Comment by BrayDog2010** [comment]
No Idea. You Can see for yourself. All you need is IntelliJ and the Minecraft Development plugin
