### ISSUE TITLE
Bundling of "Falcon Boots"

### ISSUE THREAD

**Issue by alfonsojon** [BrayDog2010/Crafting-Recipes-For-Create#5]
Why is an unrelated mod, "Falcon Boots", so often being required as a dependency of this mod? I do not feel this is appropriate.

**Comment by alfonsojon** [comment]
![image](https://github.com/user-attachments/assets/7bc6bc19-159e-435f-80c5-3da24892b18a)

**Comment by BrayDog2010** [comment]
Its been removed
